name: Build and test PR
on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and test PR
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-latest
      dotnet-version: '10.0.x'
      use-msbuild: false
      workloads: maui
      create-release: false
      install-tizen: true
      generate-build-number: false
      project-path: H.NotifyIcon.PR.slnx
